# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Ml4Qgis
                                 A QGIS plugin
 Machine learning in QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-06
        copyright            : (C) 2023 by Mikhail Moskovchenko
        email                : moskovchenkomike@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Mikhail Moskovchenko'
__date__ = '2023-05-06'
__copyright__ = '(C) 2023 by Mikhail Moskovchenko'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Ml4Qgis class from file Ml4Qgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ml4qgis import MlQgisPlugin
    return MlQgisPlugin()
